### ISSUE TITLE
Published on npmjs.com

### ISSUE THREAD

**Issue by randunel** [nicolas314/2cca#1]
Just wanted to let you know that i forked your project, added `package.json` with the compile script and published it https://www.npmjs.com/package/2cca because I used it as a dev dependency in some projects.

I haven't made any changes (other than package.json) and so far I've merged all your changes. If you want to maintain it yourself, let me know.

**Comment by nicolas314** [comment]
Hi Mihai,
Thanks for letting me know! I will keep updating the package at regular intervals to add more stuff as needs arise, so you probably want to keep sync'ing often. Glad it is useful to you!
Cheers
Nicolas
