### ISSUE TITLE
Some properties in CA cert with exclamation

### ISSUE THREAD

**Issue by dermyrddin** [nicolas314/2cca#2]
Hi, first of all thanks for python implementation for PKI!

Cert generated with python script has theese exclamations:
http://prntscr.com/cv88j3

But cert generated with EasyRSA hasn't. Is it some kind of issue?

**Comment by nicolas314** [comment]
Hi Merlin,
There should not be any difference as far as OpenVPN is concerned. I got confirmation that they do not check certificate extensions, except for clients and servers, and only if you mandate it in the configuration.
By the way: I stopped maintaining the Python script. Try out the C version instead!
Cheers
