### ISSUE TITLE
Build failed on debian

### ISSUE THREAD

**Issue by theodotos** [nicolas314/2cca#4]
I am trying to build 2cca on debian (jessie and stretch, same problem).

I installed these:

```
apt -y install build-essential libssl-dev
```

GCC version:

```
gcc --version
gcc (Debian 6.3.0-14) 6.3.0 20170415
```

libssl-dev version:

```
Version: 1.1.0e-1
```

When I compile I get:

``` 
# gcc -o 2cca 2cca.c -lcrypto
2cca.c: In function ‘build_identity’:
2cca.c:239:9: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
         rsa = RSA_generate_key(certinfo.rsa_keysz, RSA_F4, progress, 0);
         ^~~
In file included from /usr/include/openssl/rsa.h:13:0,
                 from /usr/include/openssl/x509.h:31,
                 from /usr/include/openssl/pem.h:17,
                 from 2cca.c:19:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^
2cca.c: In function ‘show_crl’:
2cca.c:398:34: error: dereferencing pointer to incomplete type ‘X509_REVOKED {aka struct x509_revoked_st}’
         i2a_ASN1_INTEGER(out, rev->serialNumber);
                                  ^~
```

Any idea?

**Comment by nicolas314** [comment]
Hi Theodotos,
Seems like I am using a function that is now deprecated in libssl. Surprising thing is: this is the first time I see this kind of warning. Usually you get a few versions between the moment a function is deprecated and the moment it is considered an error to still use it.

Anyway. I tried to reproduce the issue on a freshly installed Debian 8.8 (=stable) and seems it works fine here:

```
$ make
cc -g -Wall -o 2cca 2cca.c -lcrypto
$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
$ dpkg -l | grep libssl-dev
ii  libssl-dev:amd64               1.0.1t-1+deb8u6                    amd64        Secure Sockets Layer toolkit - development files
```
Let me try to update a VM to debian testing and see if I can reproduce it, then find a workaround.
Thanks for helping!

**Comment by nicolas314** [comment]
Oh wow, just read this:
[https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes)

Seems openssl 1.1 is breaking backwards compatibility in a lot of ways. This is not the kind of thing that is fixed with a simple #ifdef, unfortunately. For now, I will just state 2cca compiles against openssl before 1.1, and I will wait until the dust settles to produce a version compatible with the new API. Just not tonight :-)

**Comment by theodotos** [comment]
No worries. It seems that everything I try breaks :). I came to 2cca because easy-rsa is broken on debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851059

**Comment by nicolas314** [comment]
It's not you, it's openssl :-)
See also this post:
https://www.mail-archive.com/tech@openbsd.org/msg36437.html

Just checked with the new version: the changes are quite heavy, a few #ifdef's won't do. It really calls for a complete rewrite of some functions, probably ending up with two different sources. Quoting a comment on HN: "good software engineering practices and OpenSSL seem to be mutually incompatible".

I will see what I can do. In the mean time you can always compile against LibreSSL if you are patient enough to download, install, and configure the Makefile to produce a static binary to avoid conflicts with your system's openssl, but I would not recommend it.

**Comment by nicolas314** [comment]
Ok, I will stop maintaining the C version. The source you see here will forever live with openssl < 1.1.0 and that's it. I am through trying to follow these clowns.

I have rewritten from scratch a Python version that does not depend on pyopenssl, it only relies on the fact that it can find the 'openssl' command to do its magic. This should hopefully be more stable than anything that tries to use a low-level interface to OpenSSL.
For now you can generate certificates for root, subordinate, server, client, and www server. I am still missing a few nice things like emailAddress and CRL management, will include them later. The README has been updated too.

Thanks again for pointing this out! Hope you have fun with the Python version.
