### ISSUE TITLE
the generation of for root is only 1-month

### ISSUE THREAD

**Issue by wicadmin** [nicolas314/2cca#5]
Generating a root certificate seems to only allow 1-month duration. I put days=3650 and days=365 but it is not honoring it. Is this working for you?

**Comment by wicadmin** [comment]
I think it is missing in the code. I added -days 3650 to this:

```
def generate_root(cfg):
    # Generate key pair
    genkey(cfg)
    # Generate self-signed certificate
    cmd='openssl req -new -x509 -key "%(cn)s.key"' % cfg
    cmd+=' -extensions v3'
    cmd+=' -config "%(cn)s.cnf"' % cfg
    cmd+=' -sha256'
    cmd+=' -out "%(cn)s.crt"' % cfg
    cmd+=' -set_serial %s' % generate_serial()
    run(cmd)
    #os.remove('%(cn)s.cnf' % cfg)
```
Also adjusted some of the client ones that was generating approx 730 from the config info at the top of the python script as it didn't seem to be taken it from the CLI manually.

**Comment by nicolas314** [comment]
Good catch! The command-line options were just not parsed. I have added that and also days management for root.

**Comment by wicadmin** [comment]
Cool....beautiful tool man!
